version: 2.1

jobs:
  build_test:
    docker:
      - image: circleci/node:12
    steps:
      - checkout
      - run:
          name: Install npm dependencies
          command: |
            npm install --save

  build_docker_image:
    docker:
      - image: circleci/node:12
    steps:
      - checkout
      - setup_remote_docker:
          docker_layer_caching: false
      - run:
          name: Build Docker image
          command: |
            docker build -t nodejswebapp1 -t subham966/nodejswebapp1:latest .
            echo $DOCKER_PASSWORD | docker login -u subham966 --password-stdin
            docker push subham966/nodejswebapp1:latest

workflows:
  version: 2
  build_and_push:
    jobs:
      - build_test
      - build_docker_image:
          requires:
            - build_test
